---
# handlers file for auditd

- name: Run augenrules
  ansible.builtin.command:
    cmd: augenrules
  notify:
    - Load rules

- name: Load rules
  ansible.builtin.command:
    cmd: augenrules --load
  when:
    - ansible_connection not in [ "container", "docker", "community.docker.docker" ]

# systemctl can't restart auditd, service can: https://access.redhat.com/solutions/2664811
- name: Restart auditd  # noqa: command-instead-of-module
  ansible.builtin.command:
    cmd: /usr/sbin/service {{ auditd_service }} restart
  when:
    - not ansible_check_mode
